(function(global){
  'use strict';
  var scriptBase=new URL('.',document.currentScript.src);
  function asset(path){return new URL('../samples/cc0/'+path,scriptBase).href;}
  var manifest={
    acoustic:[
      {note:'E2',url:asset('freepats-nylon/e2.mp3')},{note:'A2',url:asset('freepats-nylon/a2.mp3')},{note:'D3',url:asset('freepats-nylon/d3.mp3')},
      {note:'G3',url:asset('freepats-nylon/g3.mp3')},{note:'B3',url:asset('freepats-nylon/b3.mp3')},{note:'E4',url:asset('freepats-nylon/e4.mp3')},
      {note:'A4',url:asset('freepats-nylon/a4.mp3')},{note:'D5',url:asset('freepats-nylon/d5.mp3')},{note:'G5',url:asset('freepats-nylon/g5.mp3')}
    ],
    guitar:[
      {note:'C2',url:asset('freepats-clean/c2.mp3')},{note:'F2',url:asset('freepats-clean/f2.mp3')},{note:'A2',url:asset('freepats-clean/a2.mp3')},
      {note:'C3',url:asset('freepats-clean/c3.mp3')},{note:'E3',url:asset('freepats-clean/e3.mp3')},{note:'G3',url:asset('freepats-clean/g3.mp3')},
      {note:'B3',url:asset('freepats-clean/b3.mp3')},{note:'E4',url:asset('freepats-clean/e4.mp3')},{note:'G4',url:asset('freepats-clean/g4.mp3')},
      {note:'B4',url:asset('freepats-clean/b4.mp3')},{note:'D5',url:asset('freepats-clean/d5.mp3')},{note:'G#5',url:asset('freepats-clean/gs5.mp3')},
      {note:'C#6',url:asset('freepats-clean/cs6.mp3')}
    ],
    bass:[
      {note:'E2',url:asset('big-little-bass/e2.wav')},{note:'A2',url:asset('big-little-bass/a2.wav')},
      {note:'D3',url:asset('big-little-bass/d3.wav')},{note:'G3',url:asset('big-little-bass/g3.wav')},
      {note:'C4',url:asset('big-little-bass/c4.wav')}
    ],
    piano:[
      {note:'C2',url:asset('vcsl-kawai-piano/c2.mp3')},{note:'C3',url:asset('vcsl-kawai-piano/c3.mp3')},
      {note:'G3',url:asset('vcsl-kawai-piano/g3.mp3')},{note:'D4',url:asset('vcsl-kawai-piano/d4.mp3')},
      {note:'A4',url:asset('vcsl-kawai-piano/a4.mp3')},{note:'C5',url:asset('vcsl-kawai-piano/c5.mp3')},
      {note:'C6',url:asset('vcsl-kawai-piano/c6.mp3')}
    ],
    strings:[
      {note:'D2',url:asset('vsco2-strings/d2.mp3')},{note:'C3',url:asset('vsco2-strings/c3.mp3')},
      {note:'F#3',url:asset('vsco2-strings/fs3.mp3')},{note:'C4',url:asset('vsco2-strings/c4.mp3')},
      {note:'G4',url:asset('vsco2-strings/g4.mp3')},{note:'D5',url:asset('vsco2-strings/d5.mp3')},
      {note:'C6',url:asset('vsco2-strings/c6.mp3')}
    ],
    drums:{
      kick:[asset('virtuosity-drums/browser/kick-soft.mp3'),asset('virtuosity-drums/browser/kick-hard-1.mp3'),asset('virtuosity-drums/browser/kick-hard-2.mp3')],
      snare:[asset('virtuosity-drums/browser/snare-soft.mp3'),asset('virtuosity-drums/browser/snare-mid.mp3'),asset('virtuosity-drums/browser/snare-hard.mp3')],
      rimshot:[asset('virtuosity-drums/browser/snare-rim.mp3')],
      hihat:[asset('virtuosity-drums/browser/hihat-closed-1.mp3'),asset('virtuosity-drums/browser/hihat-closed-2.mp3'),asset('virtuosity-drums/browser/hihat-closed-3.mp3')],
      openhat:[asset('virtuosity-drums/browser/hihat-open.mp3')],
      ride:[asset('virtuosity-drums/browser/ride.mp3')],ridebell:[asset('virtuosity-drums/browser/ride-bell.mp3')],
      tomhigh:[asset('virtuosity-drums/browser/tom-high-soft.mp3'),asset('virtuosity-drums/browser/tom-high-hard.mp3')],
      tomlow:[asset('virtuosity-drums/browser/tom-low-soft.mp3'),asset('virtuosity-drums/browser/tom-low-hard.mp3')],
      crash:[asset('virtuosity-drums/browser/crash.mp3')]
    }
  };
  var state={context:null,buffers:{acoustic:[],guitar:[],bass:[],piano:[],strings:[],drums:{}},jobs:null,groupLoads:{},loaded:false,failures:0,active:[],guitarIndex:{},drumIndex:{},guitarBus:null,drumBus:null,openHats:[]};
  function noteMidi(note){var match=/^([A-G])(#?)(-?\d)$/.exec(note||'');if(!match)return 69;var semis={C:0,D:2,E:4,F:5,G:7,A:9,B:11};return(Number(match[3])+1)*12+semis[match[1]]+(match[2]?1:0);}
  function midiName(midi){var names=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];return names[midi%12]+(Math.floor(midi/12)-1);}
  function decode(url){return fetch(url).then(function(response){if(!response.ok)throw new Error('HTTP '+response.status);return response.arrayBuffer();}).then(function(data){return state.context.decodeAudioData(data);});}
  function requestedGroups(requested){if(!Array.isArray(requested))return['acoustic','guitar','bass','piano','strings','drums'];var groups=[];requested.forEach(function(name){var wanted=name==='melody'?['acoustic','guitar']:name==='guitar'?['guitar']:name==='bass'?['bass']:name==='piano'?['piano']:name==='other'||name==='strings'||name==='orchestra'?['strings']:name==='drums'?['drums']:[];wanted.forEach(function(group){if(groups.indexOf(group)<0)groups.push(group);});});return groups;}
  function groupReady(group){if(group!=='drums')return(state.buffers[group]||[]).length>0;return['kick','snare','hihat'].every(function(name){return(state.buffers.drums[name]||[]).some(Boolean);});}
  function ensureJobs(context){if(state.jobs)return;state.context=context;state.jobs={acoustic:[],guitar:[],bass:[],piano:[],strings:[],drums:{}};Object.keys(manifest.drums).forEach(function(name){state.buffers.drums[name]=[];state.jobs.drums[name]=[];});}
  function noteJob(group,index){if(state.jobs[group][index])return state.jobs[group][index];var item=manifest[group][index],job=decode(item.url).then(function(buffer){state.buffers[group].push({note:item.note,midi:noteMidi(item.note),buffer:buffer});return true;}).catch(function(){state.failures++;return false;});state.jobs[group][index]=job;return job;}
  function drumJob(name,index){if(state.jobs.drums[name][index])return state.jobs.drums[name][index];var job=decode(manifest.drums[name][index]).then(function(buffer){state.buffers.drums[name][index]=buffer;return true;}).catch(function(){state.failures++;return false;});state.jobs.drums[name][index]=job;return job;}
  function coreJobs(group){if(group==='acoustic')return[noteJob('acoustic',3),noteJob('acoustic',5)];if(group==='guitar')return[noteJob('guitar',5),noteJob('guitar',7)];if(group==='bass')return[noteJob('bass',1),noteJob('bass',2)];if(group==='piano')return[noteJob('piano',2),noteJob('piano',4)];if(group==='strings')return[noteJob('strings',2),noteJob('strings',4)];return[drumJob('kick',1),drumJob('snare',1),drumJob('hihat',0)];}
  function allJobs(group){var jobs=[];if(group!=='drums')manifest[group].forEach(function(_,index){jobs.push(noteJob(group,index));});else Object.keys(manifest.drums).forEach(function(name){manifest.drums[name].forEach(function(_,index){jobs.push(drumJob(name,index));});});return jobs;}
  function load(context,requested){var groups=requestedGroups(requested);if(Array.isArray(requested)&&!groups.length)return Promise.resolve(false);ensureJobs(context);groups.sort(function(a,b){return a==='drums'?-1:b==='drums'?1:0;});var requestedLoads=[];groups.forEach(function(group){var core=coreJobs(group);if(!state.groupLoads[group])state.groupLoads[group]=Promise.all(core).then(function(){return Promise.all(allJobs(group));}).then(function(){state.loaded=['acoustic','guitar','bass','piano','strings','drums'].some(groupReady);return groupReady(group);});requestedLoads.push(state.groupLoads[group]);});return Promise.all(requestedLoads).then(function(){state.loaded=groups.some(groupReady);return groups.every(groupReady);});}
  function remember(source){state.active.push(source);source.onended=function(){var index=state.active.indexOf(source);if(index>=0)state.active.splice(index,1);};}
  function stopAll(){state.active.slice().forEach(function(source){try{source.stop();}catch(ignore){}});state.active=[];state.openHats=[];}
  function nearest(group,note){var list=state.buffers[group]||[],target=noteMidi(note),distance=Infinity,candidates=[];list.forEach(function(sample){var next=Math.abs(sample.midi-target);if(next<distance){distance=next;candidates=[sample];}else if(next===distance)candidates.push(sample);});if(!candidates.length)return null;if(group!=='guitar'&&group!=='acoustic')return candidates[0];var key=group+String(candidates[0].midi),index=state.guitarIndex[key]||0;state.guitarIndex[key]=index+1;return candidates[index%candidates.length];}
  function guitarBus(context){if(state.guitarBus&&state.context===context)return state.guitarBus;var input=context.createGain(),compressor=context.createDynamicsCompressor(),master=context.createGain(),room=context.createGain(),convolver=context.createConvolver(),roomGain=context.createGain(),echo=context.createGain(),delay=context.createDelay(.5),feedback=context.createGain(),echoGain=context.createGain(),length=Math.floor(context.sampleRate*.58),impulse=context.createBuffer(2,length,context.sampleRate);for(var channel=0;channel<2;channel++){var data=impulse.getChannelData(channel);for(var i=0;i<length;i++){var fade=Math.pow(1-i/length,3.15);data[i]=(Math.random()*2-1)*fade;}}compressor.threshold.value=-20;compressor.knee.value=15;compressor.ratio.value=2.5;compressor.attack.value=.008;compressor.release.value=.18;master.gain.value=.82;roomGain.gain.value=.16;delay.delayTime.value=.225;feedback.gain.value=.17;echoGain.gain.value=.16;convolver.buffer=impulse;input.connect(compressor);room.connect(convolver);convolver.connect(roomGain);roomGain.connect(compressor);echo.connect(delay);delay.connect(feedback);feedback.connect(delay);delay.connect(echoGain);echoGain.connect(compressor);compressor.connect(master);master.connect(context.destination);state.guitarBus={input:input,room:room,echo:echo};return state.guitarBus;}
  function playNote(context,group,note,duration,volume,offset,options){
    options=options||{};var sample=nearest(group,note);if(!sample)return false;
    var source=context.createBufferSource(),gain=context.createGain(),t=context.currentTime+(offset||0),rate=Math.pow(2,(noteMidi(note)-sample.midi)/12),available=sample.buffer.duration/rate,wanted=options.muted?Math.min(duration,.14):duration,end=t+Math.max(.05,Math.min(wanted,available-.01)),profile=options.profile||((options.drive||options.style==='rhythm')?'crunch':'clean'),profiles={acoustic:{attack:.012,sustain:.9,highpass:72,presence:2550,presenceGain:2.2,cabinet:7800,drive:0,room:.13,delay:0},clean:{attack:.008,sustain:.84,highpass:82,presence:2100,presenceGain:1.7,cabinet:6800,drive:0,room:.09,delay:.025},lead:{attack:.006,sustain:.91,highpass:86,presence:2350,presenceGain:1.9,cabinet:6200,drive:.62,room:.11,delay:.075},crunch:{attack:.006,sustain:.78,highpass:94,presence:1650,presenceGain:2.4,cabinet:4750,drive:2.35,room:.065,delay:.035},distortion:{attack:.004,sustain:.72,highpass:105,presence:1450,presenceGain:3.1,cabinet:4050,drive:4.2,room:.045,delay:.045},piano:{attack:.006,sustain:.86},strings:{attack:.075,sustain:.94}},voice=profiles[profile]||profiles.clean,humanize=options.humanize===false?0:(((group==='guitar'||group==='acoustic')?Math.random()-.5:0)*(profile==='acoustic'?2.5:profile==='lead'?2:4));source.buffer=sample.buffer;source.playbackRate.value=rate;source.detune.value=(options.pitch||0)+humanize;
    gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,volume),t+(options.muted?.003:voice.attack));gain.gain.setValueAtTime(Math.max(.0002,volume*(options.muted?.5:voice.sustain)),Math.max(t+.01,end-(options.muted?.025:.065)));gain.gain.exponentialRampToValueAtTime(.0001,end);
    if(group==='guitar'||group==='acoustic'){var bus=guitarBus(context),highpass=context.createBiquadFilter(),presence=context.createBiquadFilter(),cabinet=context.createBiquadFilter(),pan=context.createStereoPanner?context.createStereoPanner():context.createGain(),roomSend=context.createGain(),echoSend=context.createGain(),last=source;highpass.type='highpass';highpass.frequency.value=voice.highpass;presence.type='peaking';presence.frequency.value=voice.presence;presence.Q.value=.8;presence.gain.value=options.muted?-1.5:voice.presenceGain;cabinet.type='lowpass';cabinet.Q.value=profile==='acoustic'?.55:.85;cabinet.frequency.value=voice.cabinet;if(voice.drive>0){var drive=context.createWaveShaper(),curve=new Float32Array(1024),amount=voice.drive*(options.strong?1.16:1);for(var i=0;i<curve.length;i++){var x=i*2/(curve.length-1)-1;curve[i]=Math.tanh(x*amount)/Math.tanh(amount);}drive.curve=curve;drive.oversample='4x';last.connect(drive);last=drive;}last.connect(highpass);highpass.connect(presence);presence.connect(cabinet);cabinet.connect(pan);if(pan.pan)pan.pan.value=Math.max(-1,Math.min(1,options.pan||0));pan.connect(gain);gain.connect(bus.input);roomSend.gain.value=typeof options.room==='number'?options.room:voice.room;echoSend.gain.value=typeof options.delay==='number'?options.delay:voice.delay;gain.connect(roomSend);roomSend.connect(bus.room);gain.connect(echoSend);echoSend.connect(bus.echo);if(options.vibrato){var lfo=context.createOscillator(),depth=context.createGain();lfo.frequency.value=5.1;depth.gain.value=options.vibrato===true?7:options.vibrato;lfo.connect(depth);depth.connect(source.detune);lfo.start(t+Math.min(.2,wanted*.32));lfo.stop(end);}}else{source.connect(gain);gain.connect(context.destination);}
    remember(source);source.start(t);source.stop(end+.015);return true;
  }
  function playFreq(context,group,freq,duration,volume,offset,options){return playNote(context,group,midiName(Math.round(69+12*Math.log(freq/440)/Math.LN2)),duration,volume,offset,options);}
  function playStrum(context,notes,duration,volume,offset,options){options=options||{};if(!Array.isArray(notes)||!notes.length)return false;var ordered=notes.slice();if(options.direction==='up')ordered.reverse();var spread=typeof options.spread==='number'?options.spread:(options.muted?.009:.014),played=false,style=options.style||'rhythm',profile=options.profile||'crunch';ordered.forEach(function(note,index){var position=ordered.length>1?index/(ordered.length-1):.5,pan=(position-.5)*.34*(options.direction==='up'?-1:1),level=volume*(.7+.25*Math.sin((position+.15)*Math.PI));played=playNote(context,'guitar',typeof note==='number'?midiName(note):note,duration,level,(offset||0)+index*spread,{style:style,profile:profile,strong:!!options.strong,muted:!!options.muted,room:typeof options.room==='number'?options.room:undefined,delay:typeof options.delay==='number'?options.delay:undefined,pan:pan,pitch:(index%2?2:-2)})||played;});return played;}
  function drumBus(context){if(state.drumBus&&state.context===context)return state.drumBus;var input=context.createGain(),compressor=context.createDynamicsCompressor(),master=context.createGain(),room=context.createGain(),convolver=context.createConvolver(),roomGain=context.createGain(),length=Math.floor(context.sampleRate*.72),impulse=context.createBuffer(2,length,context.sampleRate);for(var channel=0;channel<2;channel++){var data=impulse.getChannelData(channel);for(var i=0;i<length;i++){var fade=Math.pow(1-i/length,2.7);data[i]=(Math.random()*2-1)*fade;}}compressor.threshold.value=-18;compressor.knee.value=16;compressor.ratio.value=3.2;compressor.attack.value=.004;compressor.release.value=.16;master.gain.value=.84;roomGain.gain.value=.11;convolver.buffer=impulse;input.connect(compressor);room.connect(convolver);convolver.connect(roomGain);roomGain.connect(compressor);compressor.connect(master);master.connect(context.destination);state.drumBus={input:input,room:room};return state.drumBus;}
  function chooseDrum(name,velocity){var list=(state.buffers.drums[name]||[]).filter(Boolean);if(!list.length)return null;var counter=state.drumIndex[name]||0,index=counter%list.length;if((name==='kick'||name==='snare'||name==='tomhigh'||name==='tomlow')&&list.length>1){if(velocity<.55)index=0;else if(velocity>.82)index=list.length-1;else index=Math.min(1,list.length-1);}else if(name==='hihat')index=(counter+(velocity>.78?2:0))%list.length;state.drumIndex[name]=counter+1;return list[index];}
  function playDrum(context,name,volume,offset,options){options=options||{};var velocity=typeof options.velocity==='number'?options.velocity:.75,buffer=chooseDrum(name,velocity);if(!buffer)return false;var bus=drumBus(context),source=context.createBufferSource(),filter=context.createBiquadFilter(),pan=context.createStereoPanner?context.createStereoPanner():context.createGain(),gain=context.createGain(),send=context.createGain(),t=context.currentTime+(offset||0),durations={kick:.62,snare:.72,rimshot:.55,hihat:.16,openhat:.85,ride:1.25,ridebell:.95,tomhigh:.72,tomlow:.88,crash:3.1},duration=Math.min(buffer.duration,options.duration||durations[name]||.8);source.buffer=buffer;source.playbackRate.value=Math.pow(2,(options.pitch||0)/1200);if(name==='kick'){filter.type='lowshelf';filter.frequency.value=95;filter.gain.value=3.5;}else if(name==='hihat'||name==='openhat'||name==='ride'||name==='ridebell'||name==='crash'){filter.type='highpass';filter.frequency.value=name==='hihat'?3200:900;}else{filter.type='peaking';filter.frequency.value=name.indexOf('tom')===0?180:210;filter.Q.value=.85;filter.gain.value=1.8;}if(pan.pan)pan.pan.value=Math.max(-1,Math.min(1,options.pan||0));gain.gain.setValueAtTime(Math.max(.0001,volume),t);gain.gain.setValueAtTime(Math.max(.0001,volume*.88),Math.max(t+.01,t+duration-.08));gain.gain.exponentialRampToValueAtTime(.0001,t+duration);send.gain.value=typeof options.room==='number'?options.room:(name==='kick'?.025:name==='hihat'?.05:.1);source.connect(filter);filter.connect(pan);pan.connect(gain);gain.connect(bus.input);gain.connect(send);send.connect(bus.room);if(name==='hihat'){state.openHats.slice().forEach(function(open){try{open.stop(t+.025);}catch(ignore){}});state.openHats=[];}if(name==='openhat')state.openHats.push(source);remember(source);source.start(t);source.stop(t+duration+.02);return true;}
  function status(requested){var groups=requestedGroups(requested),loaded=groups.length?groups.every(groupReady):state.loaded;return{loaded:loaded,failures:state.failures};}
  global.KCSampler={load:load,playNote:playNote,playFreq:playFreq,playStrum:playStrum,playDrum:playDrum,stopAll:stopAll,status:status};
})(window);
